### PR TITLE
Renamed Environment to Factory for Laravel 4.2

### PR DESCRIPTION
**Pull request by dalabarge**
Hadn't actually used it yet... it's amazing how such simple classes can be broken by such simple upstream changes.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I was just about to do that. :+1: I'll delete my fork then.

**Comment by crhayes** [comment]
Thanks guys, appreciate it!

**Comment by younes0** [comment]
Got `Call to undefined method Illuminate\View\Factory::renderPartial()` with latest Laravel

**Comment by younes0** [comment]
Please see #5

**Pull request merged**
